Stfc user office project#4 send smtp mail
UserOfficeProject/user-office-backend pull request #132
Opened 2021-01-20 13:37 UTC by Scott-James-Hurley

ref: UserOfficeProject/stfc-user-office-project#4

This adds the ability to send emails using the SMTP protocol, though Sparkpost is still the default. This is so STFC users of ESS can be sent emails. The host, port, sending address and username and password for authentication are passed via environment variables. Sparkpost has been wrapped in a class to make it a bit easier to use. The SMTP mail functionality has been testing using Jest.

2021-01-21 16:59 UTC, TickleThePanda requested changes

2021-01-21 16:59 UTC, TickleThePanda commented on src/eventHandlers/emails/submit/html.pug
> +<meta http-equiv="Content-Type" content="text/html; charset=utf-8">You have been included on a proposal for experimental time at the ESS by <b>#{piPreferredname} #{piLastname}</b><p></p><p>As the Pri
While we've been informally calling this software the "ESS proposal software", for us, we're intending it to be used at our facilities (ISIS and the different areas of the CLF). For now, could you remove mentions of the ESS in here?

I think it would also be useful to replace `<br>` with `<p>` (you only need 1 `<p>` for each paragraph rather than the multiple `<br>`s) and `<b>` with `<strong>` as that's best practice for "semantic HTML".

2021-01-27 08:46 UTC, TickleThePanda requested changes

2021-01-27 08:46 UTC, TickleThePanda commented on src/eventHandlers/emails/submit/html.pug
> +<p>As the Principal Investigator on an ESS proposal you have specific responsibilities for the experiment.<br>
I don't think we should have any `<br>` tags at all in here. For now, if that means there's poor style, I don't think it's an issue.

2021-02-04 15:22 UTC, TickleThePanda requested changes

2021-02-04 15:22 UTC, TickleThePanda commented on src/eventHandlers/MailService/SMTPMailService.ts
> +    options.content.template_id =
The directory for where the templates come from should be externalised. Probably in an env variable?

2021-02-05 10:43 UTC, Scott-James-Hurley commented on src/eventHandlers/MailService/SMTPMailService.ts
> +    options.content.template_id =
Changed SMTPMailService.ts line 57 to use an environment variable.

2021-02-09 13:25 UTC, mr-field commented
@Scott-James-Hurley Could yo try to solve the merge conflicts and push this branch again to see if that unlocks the tests?

2021-02-15 11:13 UTC, Scott-James-Hurley commented
@mr-field I've merged it with the latest version of develop. The tests pass but the build job fails.

2021-02-17 12:08 UTC, mr-field requested changes
The build is failing because the build script tries to use the branch name as a tag for the built Docker image. Unfortunately, this branch has a `#` in the name which isn't a valid character for Docker tags. The only way around it would be to close this PR, rename the branch, and create a new PR from the renamed branch. However, I think we should finish the review first to avoid confusion

2021-02-17 12:08 UTC, mr-field commented on src/eventHandlers/MailService/SMTPMailService.ts
> +      sendMailResults.id = 'test';
Since this case is specifically for unit testing, could the check be changed to `process.env.NODE_ENV === 'test'`? That way it won't affect the dev environment once we have it

2021-02-18 09:40 UTC, Scott-James-Hurley commented on src/eventHandlers/email.ts
> +  dotenv.config();
yeah you right

2021-02-18 10:21 UTC, mr-field requested changes
Thanks, one last thing

2021-02-18 10:21 UTC, mr-field commented on package.json
> -    "dotenv": "^8.2.0",
I think this is still referenced in `index.ts`. Not sure if it's actually used, but removing it will likely make "clean" builds fail

2021-02-18 13:21 UTC, mr-field approved these changes

2021-02-18 13:23 UTC, mr-field commented
@TickleThePanda Could you review this again before we reopen the PR with a renamed branch?

2021-02-24 11:04 UTC, TickleThePanda approved these changes

2021-02-24 13:27 UTC, closed without merging