WIP: Add table for units with delete,get and create endpoints
UserOfficeProject/user-office-backend pull request #160
Opened 2021-02-04 15:22 UTC by bolmsten

## Description

As a user officer I can now add units in the GUI instead of code

## Motivation and Context

The possibility of adding units in GUI will reduce the need for development effort each time a unit is added

## How Has This Been Tested

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-02-08 08:06 UTC, martin-trajanovski requested changes

2021-02-08 08:06 UTC, martin-trajanovski commented on src/datasources/postgres/AdminDataSource.ts
> +    return database
I see `await` is used in the previous two functions and it could be used here as well to keep the consistency. And not sure why we need to use two `orderBy` methods.

2021-02-08 08:06 UTC, martin-trajanovski commented on src/mutations/AdminMutations.ts
> +    //Do checks here to not delete a unit used
Isn't this required from the beginning (to do the checks if unit is used) or it can be done later?

2021-02-08 12:05 UTC, bolmsten commented on src/datasources/postgres/AdminDataSource.ts
> +      throw new Error('Could not create call');
changed

2021-02-08 12:05 UTC, bolmsten commented on src/datasources/postgres/AdminDataSource.ts
> +      throw new Error(`Could not delete institution with id:${id}`);
changed

2021-02-08 12:06 UTC, bolmsten commented on src/mutations/AdminMutations.ts
> +    //Do checks here to not delete a unit used
It does not need to check as the answer and options is stored with the question.

2021-02-08 13:31 UTC, martin-trajanovski approved these changes

2021-02-09 10:07 UTC, jekabs-karklins approved these changes
Looks great

2021-02-09 10:07 UTC, jekabs-karklins commented on db_patches/0078_AddUnits.sql
> +    INSERT INTO units (unit) values ('kelvin');
Will the remaining units be added through the UI?

2021-02-10 08:34 UTC, bolmsten commented on db_patches/0078_AddUnits.sql
> +    INSERT INTO units (unit) values ('kelvin');
yes, but added these for the E2E test

2021-02-17 13:24 UTC, merged