Swap 1306
UserOfficeProject/user-office-backend pull request #209
Opened 2021-03-09 09:54 UTC by peter-asztalos

## Description

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-03-11 10:40 UTC, martin-trajanovski approved these changes
Looks good! 💯

2021-03-12 18:03 UTC, jekabs-karklins requested changes

2021-03-12 18:03 UTC, jekabs-karklins commented on example.env
> +UO_FEATURE_DISABLE_EAM=1
+1

2021-03-12 18:03 UTC, jekabs-karklins commented on example.env
> +secret=qMyLZALzs229ybdQXNyzYRdju7X784TH
It's best practice not to place any passwords or secrets into the repository, even if they are not working/dangerous. This is because secrets like this encourage curiosity for poking arround.

2021-03-18 08:39 UTC, peter-asztalos commented on example.env
> +secret=qMyLZALzs229ybdQXNyzYRdju7X784TH
I totally agree with you, but in this case, the secret is already part of the git history and is already part of other files. As this secret is used by the token we use for e2e testing, I think the best is to have it here as a default value. Ofc. we have to make sure we don't use it anywhere else (testing, prod).

2021-03-18 08:43 UTC, peter-asztalos commented on docker-compose.yml
> +      - "33000:80" # The HTTP port
Previously this part was used to bootstrap a totally functioning UO, including already deployed docker images (if we want to have things like this we should use a different docker-compose file), but this now used for accessing the scheduler UI. Since the port we use on FE is 3000 for development, I thought having a similar one is better, and there is less chance we would have a port conflict.

2021-03-18 08:44 UTC, peter-asztalos commented on docker-compose.yml
> +    image: "dmsc/duo-gateway:SWAP-1306"
only for testing, will fix it before merge

2021-03-19 16:22 UTC, Scott-James-Hurley approved these changes

2021-03-22 10:03 UTC, jekabs-karklins approved these changes

2021-03-22 12:31 UTC, merged