Swap 1396 change status on multiple proposals
UserOfficeProject/user-office-backend pull request #219
Opened 2021-03-18 07:32 UTC by martin-trajanovski

## Description

Status change on multiple proposals at once

## Motivation and Context

Previously if you wanted to change proposal status you should do it manually one by one proposal.

## How Has This Been Tested

- e2e tests
- manual tests

## Fixes

https://jira.esss.lu.se/browse/SWAP-1396

## Tests included/Docs Updated?

- [x] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-03-18 13:14 UTC, jekabs-karklins approved these changes

2021-03-19 10:15 UTC, peter-asztalos requested changes

2021-03-19 10:15 UTC, peter-asztalos commented on src/mutations/ProposalMutations.ts
> +      proposals.forEach(async (proposal) => {
this should be `await Promise.all` and `.map`,

2021-03-19 12:56 UTC, martin-trajanovski commented on src/mutations/ProposalMutations.ts
> +      proposals.forEach(async (proposal) => {
@peter-asztalos resolved! Good catch and while testing I found another small issue.

2021-03-19 13:01 UTC, peter-asztalos approved these changes

2021-03-19 15:08 UTC, merged