Swap 1479 fixing proposal workflow bugs
UserOfficeProject/user-office-backend pull request #243
Opened 2021-04-01 12:40 UTC by martin-trajanovski

## Description

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-04-07 10:10 UTC, jekabs-karklins requested changes
Looks good except the missing `await`

2021-04-07 10:10 UTC, jekabs-karklins commented on src/datasources/mockups/ProposalSettingsDataSource.ts
> +    }: {
I see you use this type several times. Maybe it makes sense to factor it out into separate file and then reuse the interface

2021-04-07 10:10 UTC, jekabs-karklins commented on src/mutations/InstrumentMutations.ts
> +      !this.userAuth.isUserOfficer(agent) &&
aren't you missing `await` here?

2021-04-07 11:48 UTC, martin-trajanovski commented on src/mutations/InstrumentMutations.ts
> +      !this.userAuth.isUserOfficer(agent) &&
This function isUserOfficer is not an async function. It just checks if that person has that specific role in current role.

2021-04-09 17:01 UTC, jekabs-karklins approved these changes

2021-04-12 06:27 UTC, merged