SWAP-1366 If trying to edit a proposal whose call is ended returns an error
UserOfficeProject/user-office-backend pull request #262
Opened 2021-04-16 09:16 UTC by peter-asztalos

## Description

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-04-19 10:58 UTC, simonfernandes approved these changes

2021-04-21 13:41 UTC, jekabs-karklins approved these changes

2021-04-21 13:48 UTC, jekabs-karklins requested changes
I think we should move this logic into QuestionaryAuthorization

2021-04-21 13:52 UTC, jekabs-karklins commented on src/mutations/QuestionaryMutations.ts
> +      template.templateId === TemplateCategoryId.PROPOSAL_QUESTIONARY &&
This should be like `template.categoryId === TemplateCategoryId.PROPOSAL_QUESTIONARY` , but I think it's best to move these things from Mutation to QuestionaryAuthorizer, it will simplify

2021-04-26 09:49 UTC, martin-trajanovski approved these changes

2021-04-27 06:40 UTC, merged