81 update proposal editor interface to improve clarity
UserOfficeProject/user-office-backend pull request #342
Opened 2021-06-25 09:20 UTC by simonfernandes

## Description

Frontend branch: https://github.com/UserOfficeProject/user-office-frontend/pull/403

## Motivation and Context

To enable checking whether a proposal will have an upcoming editable submitted status and display a different submit button confirmation to the user.

## How Has This Been Tested

Tested manually

## Fixes

## Changes

- Remove user auth to enable the editable submitted check from a user account
- Made status changing events on a connection optional, as not all connections have them (the default draft status for example)

## Depends on

https://github.com/UserOfficeProject/user-office-frontend/pull/403

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-06-29 06:47 UTC, jekabs-karklins commented on src/queries/ProposalSettingsQueries.ts
> -  @Authorized([Roles.USER_OFFICER])
@martin-trajanovski  what do you think about this? Is it ok to remove it?

2021-06-29 07:59 UTC, martin-trajanovski commented on src/queries/ProposalSettingsQueries.ts
> -  @Authorized([Roles.USER_OFFICER])
Hmm not sure why it needs to be removed. Because for now we allow only user officers to create workflow groups. Not sure what is the initial reason for removal.

2021-06-29 09:53 UTC, jekabs-karklins commented on src/queries/ProposalSettingsQueries.ts
> -  @Authorized([Roles.USER_OFFICER])
It says in the description:
`Remove user auth to enable the editable submitted check from a user account`
I was wondering @martin-trajanovski if there are any security risks for exposing this?

2021-06-29 09:57 UTC, martin-trajanovski commented on src/queries/ProposalSettingsQueries.ts
> -  @Authorized([Roles.USER_OFFICER])
I think it should keep at least the `Authorized` without any role just to prevent any risks from unauthorized access to some data.

2021-06-29 09:58 UTC, martin-trajanovski requested changes
Keep `Authorized` decorator at the `proposalWorkflowConnectionGroups` query just remove the role to prevent unauthorized access to the data.

2021-06-30 14:15 UTC, martin-trajanovski approved these changes

2021-07-07 07:50 UTC, merged