fix(tepmlates): Improving archived templates queries
UserOfficeProject/user-office-backend pull request #352
Opened 2021-07-12 13:59 UTC by martin-trajanovski

## Description

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-07-13 13:52 UTC, jekabs-karklins requested changes

2021-07-13 13:52 UTC, jekabs-karklins commented on src/datasources/postgres/TemplateDataSource.ts
> +  async getTemplate(templateId?: number) {
I think `templateId` should not be optional for the getTemplate

It it is not set, it will return unexpected results

2021-07-13 13:52 UTC, jekabs-karklins commented on src/queries/TemplateQueries.ts
> +    @inject(Tokens.TemplateDataSource) public dataSource: TemplateDataSource
I think it is better to keep the parameter private and resolve the dependency where you need it with
`container.resolve(TemplateDataSource)`

2021-07-13 13:52 UTC, jekabs-karklins commented on src/resolvers/queries/ProposalTemplatesQuery.ts
> +  @Field(() => [Int], { nullable: true })
This should be `@Field(() => [Int!], { nullable: true })`

2021-07-14 08:03 UTC, martin-trajanovski commented on src/resolvers/queries/ProposalTemplatesQuery.ts
> +  @Field(() => [Int], { nullable: true })
I think this is how it should be on the frontend here it is not allowed to use `Int!`

2021-07-14 11:47 UTC, jekabs-karklins approved these changes

2021-07-14 11:47 UTC, jekabs-karklins commented on src/datasources/postgres/TemplateDataSource.ts
> +          query.where({ is_archived: args.filter?.isArchived });
I think you can skip optional chaining since it's already checked in the if statement
`query.where({ is_archived: args.filter.isArchived });`

2021-07-19 07:13 UTC, jekabs-karklins commented on src/resolvers/types/Call.ts
> +  @Field(() => Int)
If this is not optional, then I suggest we also mark it as non-optional in the `createCallMutation`

2021-07-19 07:20 UTC, martin-trajanovski commented on src/resolvers/types/Call.ts
> +  @Field(() => Int)
It is done in the next PR. It is a bit separated but the next one is more about that making template as reqiured. This one is just for showing archived templates.

2021-07-20 07:04 UTC, merged