Added attachment for footer logo
UserOfficeProject/user-office-backend pull request #385
Opened 2021-08-12 17:04 UTC by vyshnavi1605

## Description

Closes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/52
I added an image attachment into the email template. So that there will be an image displayed in the footer of the confirmation email. 

## How Has This Been Tested
The way this has been done is through submitting proposals on the new proposals system. Once a proposal is submitted the BusAppsSinks inbox receives a confirmation email that I checked to see if it had the correct format. 

## Changes
- Added the links to the email and changed the wording of the email in the `html.pug` file
- Added an image to the footer which was then added to `html.pug`.
- Added the `styles.css` sheet and sized the logo. 

Branch Name: stfc-user-office-project_52_amend_confirmation_email_format

2021-08-13 09:02 UTC, TickleThePanda requested changes

2021-08-19 15:13 UTC, TCMeldrum commented
What should the logo path be on dev? EMAIL_FOOTER_IMAGE_PATH isn't set in the dev config file. Do we also need to add these changes to BIS\kubernetes-shared-dev\BisAppSettings or is that done automatically as part of the dev deployment?

2021-08-20 06:23 UTC, vyshnavi1605 commented
> What should the logo path be on dev? EMAIL_FOOTER_IMAGE_PATH isn't set in the dev config file. Do we also need to add these changes to BIS\kubernetes-shared-dev\BisAppSettings or is that done automatically as part of the dev deployment?

I added the logo path only in the local dev file. I'm not entirely sure if it will get added automatically, I can add the path to both or just the dev config file. What would you suggest?

2021-08-25 08:33 UTC, TickleThePanda approved these changes

2021-08-25 08:33 UTC, TickleThePanda commented
I don't think the ESS team need to look at this one so you're welcome to merge whenever you're ready.

2021-08-25 11:59 UTC, TCMeldrum approved these changes

2021-08-25 14:59 UTC, merged