#173 Display name instead of ID in toolbar
UserOfficeProject/user-office-backend pull request #400
Opened 2021-09-06 07:47 UTC by TeraMike

## Description

When the external token is checked, a dummyUser is created as required for the database. This is saved as before, but now when returned this user gets the email, firstname, and lastname from the stfcUser added to it.  
I considered doing this in a datasource (so as to return a usable user from e.g.: ensureDummyUserExists) but couldn't find a neater way of doing it nor one that really fit the function -- open to ideas if there is a preferable alternative.

See frontend PR for screenshot.

## Fixes

Fixes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/173

## Depends on

PR for the toolbar changes in the frontend:

2021-09-06 08:33 UTC, TCMeldrum approved these changes

2021-09-06 08:45 UTC, ACLay requested changes
We actually have two first name fields in our users system, and it looks like this one does too.

In our current ones it's [`givenName` and `firstNameKnownAs`](https://github.com/isisbusapps/Users/blob/d6b401637298ceac6c1ea8af74380dc4c0f39d7a/users/users-model-ejb/src/main/java/com/stfc/UserOffice/dtos/PersonDetailsDTO.java#L18), and the here it's [`firstname` and `preferredname`](https://github.com/UserOfficeProject/user-office-backend/blob/89f7d72f6dcc3f4c254a4e2e1280de40f024d96a/src/resolvers/types/User.ts#L53)

Could you set that extra field on the dummyUser, and have the frontend use preferredname if it's been set instead of firstname?

2021-09-06 08:52 UTC, TeraMike commented
> In our current ones it's [`givenName` and `firstNameKnownAs`](https://github.com/isisbusapps/Users/blob/d6b401637298ceac6c1ea8af74380dc4c0f39d7a/users/users-model-ejb/src/main/java/com/stfc/UserOffice/dtos/PersonDetailsDTO.java#L18), and the here it's [`firstname` and `preferredname`](https://github.com/UserOfficeProject/user-office-backend/blob/89f7d72f6dcc3f4c254a4e2e1280de40f024d96a/src/resolvers/types/User.ts#L53)


Oh that's a good shout, I completely missed those since the different names just didn't register as the same thing in my head. I'll do that.

2021-09-06 10:10 UTC, ACLay approved these changes

2021-09-06 13:24 UTC, TickleThePanda requested changes

2021-09-06 13:24 UTC, TickleThePanda commented on src/mutations/UserMutations.ts
> +      // add user info to dummmyUser for UserContext
Will this persist the data to the database? I'm guessing not but can we make the comment here clear to say that we shouldn't?

We should avoid storing any additional personal data in this database as we manage databases with personal data slightly different.

2021-09-06 13:47 UTC, TeraMike commented on src/mutations/UserMutations.ts
> +      // add user info to dummmyUser for UserContext
No, this shouldn't persist the data since the dummyUser is created / written to database in the `ensureDummyUserExists` rabbithole above, which I haven't changed. This is done on login, checking the external token in `ExternalAuth`, which then handles login from the `UserContextProvider` file.

I'll change the comment to make this more clear.

2021-09-07 09:17 UTC, TeraMike commented on src/mutations/UserMutations.ts
> +      // add user info to dummmyUser for UserContext
@TickleThePanda does this look alright now?

2021-09-07 09:27 UTC, TickleThePanda approved these changes

2021-09-08 12:54 UTC, merged