Swap 495 as a user i should only see the public status of my proposal
UserOfficeProject/user-office-backend pull request #45
Opened 2020-10-26 12:33 UTC by jekabs-karklins

## Description

User should only be able to see the public status of the proposal;

## Motivation and Context

We do not want to show user in which stage the proposal is in, because that is irrelevant and confusing for the user.
User only needs to see if the proposal is in the draft, submitted, accepted,  rejected or reserved

## How Has This Been Tested

e2e testing

## Fixes

https://jira.esss.lu.se/browse/SWAP-495
As a user I should only see if my proposal is in draft, submitted, rejected, Reserve or accepted
# Remove column submitted,
# In status show DRAFT, SUBMITTED and (ACCEPTED/REJECTED)
# All other statuses between SUBMITTED and ACCEPTED/REJECTED should be simply displayed as SUBMITTED
# Fix that status is always shown as DRAFT

## Changes

Adding new queryable field - public status

## Tests included/Docs Updated?

New tests:
User should see the right status for the draft proposal
User should see the right status for the submitted proposal

- [x] I have added tests to cover my changes.
- [x] All relevant doc has been updated

2020-10-26 12:58 UTC, jekabs-karklins commented on src/queries/ProposalQueries.ts
> +  async getPublicStatus(agent: UserWithRole | null, id: number) {
@bolmsten This is how the public status is determined

2020-10-27 15:22 UTC, ACLay requested changes

2020-10-27 15:22 UTC, ACLay commented on src/datasources/mockups/ProposalDataSource.ts
> +    dummyProposal = dummyProposalFactory({ id: 1 });
Is this argument needed? The factory uses 1 as the default id

2020-10-27 15:22 UTC, ACLay commented on src/datasources/mockups/ProposalDataSource.ts
> +      [dummyProposal, dummyProposalSubmitted].find(
Should this be `allProposals.find` ?

2020-10-27 15:22 UTC, ACLay commented on src/models/Proposal.ts
> +export enum ProposalPublicStatus {
It isn't clear to me what the difference is between `ProposalPublicStatus` and `ProposalEndStatus`. Could some comments be added to clarify what they are intended for?

2020-10-29 08:03 UTC, jekabs-karklins commented on src/datasources/mockups/ProposalDataSource.ts
> +    dummyProposal = dummyProposalFactory({ id: 1 });
Yes, from a code perspective not needed, and I thought about passing no arguments, but I believe it's just a little more readable because the other has id:2

2020-10-29 08:32 UTC, jekabs-karklins commented on src/datasources/mockups/ProposalDataSource.ts
> +      [dummyProposal, dummyProposalSubmitted].find(
Thanks.

2020-10-29 08:41 UTC, jekabs-karklins commented on src/models/Proposal.ts
> +export enum ProposalPublicStatus {
Yes, it should be documented somewhere although at the moment I'm not sure where to place this. 

@martin-trajanovski correct if I'm wrong or you have other thoughts but ProposalEndStatus is something set by the user officer to indicate the final status of the proposal. ProposalPublicStatus is something communicated back to a user. Although they mostly have the same value, they are conceptually different. Also worth noting that PublicStatus is not something stored in the DB but rather a derived value.

2020-11-02 07:24 UTC, martin-trajanovski approved these changes

2020-11-02 07:56 UTC, peter-asztalos approved these changes

2020-11-02 10:25 UTC, ACLay commented on src/models/Proposal.ts
> +export enum ProposalPublicStatus {
Even if it's not the final form of documentation, I still think it would be useful to have some comments around these enums explaining their purposes and what makes them different.

2020-11-04 12:58 UTC, jekabs-karklins commented on src/models/Proposal.ts
> +export enum ProposalPublicStatus {
@ACLay I added the descriptions for the 3 proposal statuses we have now, but there is currently work around it, so they are subject to change

2020-11-04 13:57 UTC, ACLay approved these changes

2020-11-05 06:56 UTC, merged