fix: SMTP emails not sending
UserOfficeProject/user-office-backend pull request #472
Opened 2021-11-10 16:36 UTC by simonfernandes

Part of UserOfficeProject/stfc-user-office-project#233

## Description

This fixes emails not being sent locally only (tested). 

I assume this will also be needed for the dev and prod emails which are also broken, but I'm unable to test that and it additionally requires 

I think this may have stopped working when we switched to Linux containers.

## Motivation and Context

## How Has This Been Tested

Emails send locally only

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-11-10 16:44 UTC, ACLay requested changes
To ensure that any future changes to the config path don't cause this to pop up again can you switch this to use a path handler library rather than just concatenating strings? It looks like we already have one in use elsewhere in the backend: https://github.com/UserOfficeProject/user-office-backend/blob/df93e842224e35ef9a987e54f66af073083aecaf/src/datasources/postgres/AdminDataSource.ts#L37

2021-11-10 16:44 UTC, TickleThePanda submitted a review, later dismissed

2021-11-10 16:44 UTC, TickleThePanda commented on src/eventHandlers/MailService/SMTPMailService.ts
> +        options.content.template_id + '/html.pug'
Could we use `path.join(options.content.template_id, 'html.pug')` here?

I think path can be imported as:
```
import * as path from 'path';
```

2021-11-12 14:34 UTC, ACLay approved these changes

2021-11-15 13:13 UTC, merged