Add import functionality
UserOfficeProject/user-office-backend pull request #489
Opened 2021-11-19 11:26 UTC by EdwardHaynes

## Description
Refs: https://github.com/UserOfficeProject/stfc-user-office-project/issues/122

Added functionality for the legacy proposal import.

## Motivation and Context

## How Has This Been Tested

## Changes

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-11-19 12:11 UTC, TCMeldrum approved these changes
Looks good as far as I can tell. Do we have a script or something to run for importing the data?

2021-11-19 12:13 UTC, simonfernandes approved these changes

2021-11-19 12:14 UTC, mr-field requested changes

2021-11-19 12:14 UTC, mr-field commented on src/datasources/ProposalDataSource.ts
> +  submitProposal(primaryKey: number, legacyReferenceNumber?: string): Promise<Proposal>;
Could you rename `legacyReferenceNumber` to just `referenceNumber`? It seems that whatever is passed will end up and the proposal's reference, so it doesn't necessarily have to be a legacy number

2021-11-19 12:14 UTC, mr-field commented on src/mutations/ProposalMutations.ts
> +  //@EventBus(Event.PROPOSAL_SUBMITTED)
Are these decoratiors meant to be commented out? If so, can they be removed?

2021-11-19 12:14 UTC, mr-field commented on src/mutations/ProposalMutations.ts
> +      return rejection("...", {});
Could we give this rejection a more user-friendly message - like "Could not update proposal"?

2021-11-19 12:15 UTC, ACLay submitted a review, later dismissed

2021-11-19 12:15 UTC, ACLay commented on .eslintrc.json
> +        "es2021": true
The [Contribution guide](https://github.com/UserOfficeProject/user-office-backend/blob/develop/CONTRIBUTING.md) says we're targeting ES2015

2021-11-19 12:15 UTC, ACLay commented on src/mutations/ProposalMutations.ts
> +  //@ValidateArgs(createProposalValidationSchema)
New commented out code. Can this be removed?

2021-11-19 12:15 UTC, ACLay commented on src/mutations/ProposalMutations.ts
> +    const { callId, submitterId, proposerId, referenceNumber, users } = args;
Can the users field be renamed? By the name I'd expect it to be user objects, but it seems to be user numbers/ids instead

2021-11-19 12:15 UTC, ACLay commented on src/mutations/ProposalMutations.ts
> +      }
Can this bit be done as a `Promise.all` block like the above existence check?

2021-11-19 12:15 UTC, ACLay commented on src/mutations/ProposalMutations.spec.ts
> +  ).toHaveProperty('title', 'new title');
It looks to me like the `import` method returns a proposal promise. If that's the case, can we check the title property on the returned proposal directly, rather than introducing this new `proposalsUpdated` list?

2021-11-19 12:56 UTC, TickleThePanda commented on src/mutations/ProposalMutations.spec.ts
> +  ).toHaveProperty('title', 'new title');
I'm skipping this one as I'm keen to get this merged in and the mocked data source doesn't particularly play well with this.

2021-11-19 13:03 UTC, mr-field requested changes

2021-11-19 13:03 UTC, mr-field commented on src/datasources/mockups/ProposalDataSource.ts
> +    legacyReferenceNumber?: string
This should also be renamed to `referenceNumber`

2021-11-19 13:29 UTC, merged

2021-11-19 13:37 UTC, mr-field commented
This PR changed the GraphQL API, so the frontend SDK needs to be regenerated as a result. Until that's done, all E2E tests will fail.

2022-02-15 15:28 UTC, EdwardHaynes commented on .eslintrc.json
> +}
I've removed the unnecessary file