style: alter log format
UserOfficeProject/user-office-backend pull request #496
Opened 2021-11-24 15:21 UTC by simonfernandes

## Description

This is an optional PR that alters the event logger format to mirror the console logger format

Before (from STFC log server):
![image](https://user-images.githubusercontent.com/14293717/143265357-2d4a0022-1ab9-47cb-8bc2-838081c3b09f.png)

After (local log output):
![image](https://user-images.githubusercontent.com/14293717/143265227-bbf6b14b-5a82-47bb-b66c-3e9e4c5bf65e.png)

## Motivation and Context

## How Has This Been Tested

Tested by checking local log output

## Fixes

Part of UserOfficeProject/stfc-user-office-project#272

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2021-11-24 15:45 UTC, TickleThePanda requested changes

2021-11-24 15:45 UTC, TickleThePanda commented on src/eventHandlers/logging.ts
> +    console.log(`[${timestamp}] EVENT - ${json}`);
Rather than using `console.log` here, would it be worth using `logger`? Are there any other places we're using `console.log` outside of tests?

2021-11-24 16:10 UTC, simonfernandes commented on src/eventHandlers/logging.ts
> +    console.log(`[${timestamp}] EVENT - ${json}`);
I can try this. There's around 15 other instances of `console.log` in the frontend and backend.

2021-11-25 11:59 UTC, TickleThePanda commented on src/eventHandlers/logging.ts
> +    console.log(`[${timestamp}] EVENT - ${json}`);
It might be worth moving those to use the `console.log` if they're useful - or delete them instead.

2021-11-26 15:53 UTC, simonfernandes commented on src/eventHandlers/logging.ts
> +    console.log(`[${timestamp}] EVENT - ${json}`);
I've made this PR to handle events using the logger: https://github.com/UserOfficeProject/user-office-lib/pull/81. If that gets approved then I'll amend this PR to use `logger`.

Removing the remaining `console.log` statements is being handled by Cosimo as part of another issue

2021-11-29 11:40 UTC, jekabs-karklins approved these changes

2021-12-09 11:02 UTC, mr-field requested changes
I've updated this file in https://github.com/UserOfficeProject/user-office-backend/pull/507 to log all events with `duo-logger`. This ensures they follow the same format as everything else.

If the new format is OK, I think this PR should be closed. If the log messages aren't clear yet, we should solve the merge conflict here and make changes to the new log statement.

2021-12-09 11:13 UTC, simonfernandes commented
Closing as no longer necessary after #507

2021-12-09 11:13 UTC, closed without merging