Fixed the bug where User Officers could not add co-investigators to proposals
UserOfficeProject/user-office-backend pull request #553
Opened 2022-01-25 11:19 UTC by IVlaD17

## Description
Changes the STFC `getUsers` method so that it can now pull Users from the UOWS back-end.

## Motivation and Context
Closes UserOfficeProject/stfc-user-office-project#284

## How Has This Been Tested
Manual testing in the front-end.

## Depends on
UserOfficeProject/stfc-user-office-frontend#674

2022-01-28 13:53 UTC, jekabs-karklins approved these changes

2022-02-04 16:14 UTC, mr-field reviewed
In the future, it may be a good idea to add a method to the UOWS for getting the roles of a list of people. That would allow us to filter by user role, which we can't do at the moment.

2022-02-04 16:14 UTC, mr-field commented on src/datasources/stfc/StfcUserDataSource.ts
> +        : [];
Looks like the UOWS returns an empty list rather than `null` if it didn't find any results, so we should be able to skip this check: https://github.com/isisbusapps/Users/blob/bd3236cd5c8d804eb39c1e2b40951f53e4d2cd61/users/users-model-ejb/src/main/java/com/stfc/UserOffice/model/basicpersondetails/BasicPersonDetailsService.java#L210

2022-02-04 16:14 UTC, mr-field commented on src/datasources/stfc/StfcUserDataSource.ts
> +        undefined,
For future reference, this will show all users even in dialogs which should be restricted to Instrument Scientists or User Officers. I think this is OK for now, as we don't have a way of getting the roles of many users in a single call. Those dialogs are currently broken, as our roles come from the UOWS and are not set in the database: the `userRole` filter always fails as it's looking for nonexisting data.

2022-02-04 16:21 UTC, mr-field commented on src/datasources/stfc/StfcUserDataSource.ts
> +        : [];
Also, we should either do the `if (filter)` check early and return the data from the UOWS without running the DB query if we have a filter, or use `if/else` to either make the UOWS call or the DB query. Currently, the code always does the DB query and then thows away the result if there is a filter, which is not very efficient.

2022-02-04 16:21 UTC, mr-field commented on src/datasources/stfc/StfcUserDataSource.ts
> +        : [];
Also, we should either do the `if (filter)` check early and return the data from the UOWS without running the DB query if we have a filter, or use `if/else` to either make the UOWS call or the DB query. Currently, the code always does the DB query and then thows away the result if there is a filter, which is not very efficient.

2022-02-07 15:32 UTC, TCMeldrum commented on src/datasources/stfc/StfcUserDataSource.ts
> +        : [];
Cool updated do the if filter earlier and removed the check

2022-02-07 16:09 UTC, mr-field requested changes
Just a likely leftover debug message left, otherwise looks good.

2022-02-07 16:09 UTC, mr-field commented on src/datasources/stfc/StfcUserDataSource.ts
> +      console.log(finalTotalCount);
We should either log this with `duo-logger` and a clear `INFO` message, or remove it. Using the console directly doesn't record the timestamp or severity of the message, which is why we enabled to Eslint rule to ban `console` calls. `duo-logger` logs to the console anyway, so there are no downsides to using it even for debug messages.

2022-02-07 16:28 UTC, TCMeldrum commented on src/datasources/stfc/StfcUserDataSource.ts
> +      console.log(finalTotalCount);
Yeah, leftover debug message sorry

2022-02-07 16:30 UTC, mr-field approved these changes

2022-02-15 17:30 UTC, merged