Swap 1166 question order not saved
UserOfficeProject/user-office-backend pull request #60
Opened 2020-11-10 08:06 UTC by martin-trajanovski

## Description

This is a bugfix and improvement. This changes the way we are ordering and sorting the questions inside topics and topics inside a templates.

## Motivation and Context

This is bugfix and improvement in the functionality for sorting and soring sort values inside database. Previously we had problems with sorting questions and topics because if new question was added in between two questions we were just inserting the new question and not updating the sort_order for questions after it so two or more questions were ending up on the same position which wasn't good for the positioning on the frontend. Now that is solved with using random decimal numbers between previous and next item in the topic. This way the ordering of the items is more efficient and reliable.

## How Has This Been Tested

It has unit and e2e tests.

## Fixes

Fixes https://jira.esss.lu.se/browse/SWAP-1166

## Changes

There are mainly changes in the database. I change the sortOrder from Int type to Float in the graphql schema and sort_order from INT to NUMERIC with 14 decimal digits in the database.

## Tests included/Docs Updated?

- [x] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2020-11-10 10:14 UTC, peter-asztalos approved these changes

2020-11-10 11:20 UTC, jekabs-karklins approved these changes

2020-11-11 18:05 UTC, ACLay requested changes
At a high level, I'm unclear why was it chosen to switch to floats instead of updating the index values on subsequent questions/sections, and I think doing so introduces a problem.

With floats, reordering by using inbetween values could lead to the order values coalescing, and clashing once they get too close. With 8 decimals of precision I reckon this could happen after log2(10^8) ≈ 27 reorderings.

I could see this happening down the line if a template gets repeatedly copied and adapted between rounds. I don't think this sort of error could occur if we use integers and update the sort indexes of later items in the list.

2020-11-12 08:41 UTC, martin-trajanovski commented
> At a high level, I'm unclear why was it chosen to switch to floats instead of updating the index values on subsequent questions/sections, and I think doing so introduces a problem.
> 
> With floats, reordering by using inbetween values could lead to the order values coalescing, and clashing once they get too close. With 8 decimals of precision I reckon this could happen after log2(10^8) ≈ 27 reorderings.
> 
> I could see this happening down the line if a template gets repeatedly copied and adapted between rounds. I don't think this sort of error could occur if we use integers and update the sort indexes of later items in the list.

2020-11-12 08:49 UTC, martin-trajanovski commented
> At a high level, I'm unclear why was it chosen to switch to floats instead of updating the index values on subsequent questions/sections, and I think doing so introduces a problem.
> 
> With floats, reordering by using inbetween values could lead to the order values coalescing, and clashing once they get too close. With 8 decimals of precision I reckon this could happen after log2(10^8) ≈ 27 reorderings.
> 
> I could see this happening down the line if a template gets repeatedly copied and adapted between rounds. I don't think this sort of error could occur if we use integers and update the sort indexes of later items in the list.

The main issue was that we were not updating the sort indexes of later items in the list at all. I tried to research a bit and I thought that maybe this will be the most efficient solution because we wont need to update anything just insert the reordered or new item at the right position. I have seen some examples where in Trello boards they use this kind of approach. I was thinking that it will be good for our needs as well but now I see your point and I guess that it might be better to use integers and just update the entire list of items after the one changed. I will rethink and discuss with others and we will come with conclusion what works the best for us. Thank you for the comment anyway.

2020-11-19 16:28 UTC, ACLay requested changes

2020-11-19 16:28 UTC, ACLay commented on src/mutations/TemplateMutations.ts
> +      .then(data => data)
What are these `.then(data => data)` lines for? They don't look like they do anything.

2020-11-19 16:28 UTC, ACLay commented on src/populate/index.ts
> +        sortOrder: faker.random.number({
I'm guessing that this file is to create some dummy data in test/development environments?
Either way, it looks like this sortOrder generator wasn't updated to generate integers alongside the other one on line 184

2020-11-23 07:18 UTC, martin-trajanovski commented on src/mutations/TemplateMutations.ts
> +      .then(data => data)
Good catch maybe we save some lines if we remove them

2020-11-23 07:18 UTC, martin-trajanovski commented on src/populate/index.ts
> +        sortOrder: faker.random.number({
I will check and update this as well

2020-11-24 10:41 UTC, ACLay approved these changes

2020-11-24 10:51 UTC, merged