fix: Hotfix for STFC instrument assignment
UserOfficeProject/user-office-backend pull request #694
Opened 2022-07-05 08:30 UTC by simonfernandes

This fixes instrment scientists (and others) not being assigned to instruments.

We were filtering out all of the non duplicate roles, instead of the inverse. On dev and for me at least, the "User Officer" role was the only duplicate, which is probably why we didn't notice.

Part of UserOfficeProject/user-office-project-issue-tracker#628

2022-07-05 08:51 UTC, TickleThePanda requested changes

2022-07-05 08:51 UTC, TickleThePanda commented on src/auth/StfcUserAuthorization.ts
>        const uniqueRoles = stfcRoles.filter(
Is there any way we can add unit tests for this?

2022-07-05 08:51 UTC, mr-field approved these changes

2022-07-05 11:13 UTC, simonfernandes commented
I put the wrong issue number in my last commit ☹

2022-07-06 05:18 UTC, martin-trajanovski approved these changes

2022-07-06 09:26 UTC, TickleThePanda approved these changes

2022-07-06 09:27 UTC, merged