fix: Fix STFC email search
UserOfficeProject/user-office-backend pull request #699
Opened 2022-07-07 16:13 UTC by simonfernandes

## Description
(View without whitespace changes)

This is a hotfix that fixes an error when searching for a user to add as PI or Co-I, when the UOWS returns no results.

Refs UserOfficeProject/user-office-project-issue-tracker#632

## How Has This Been Tested

- Tested that a frontend error displays rather than the backend throwing an error
- Fix aligns with the backend error thrown

2022-07-07 16:17 UTC, TickleThePanda requested changes
Any chance of another unit test here for the expected behaviour from the UOWS?

2022-07-07 16:22 UTC, TickleThePanda commented on src/datasources/stfc/StfcUserDataSource.ts
>        : client.getBasicPersonDetailsFromEmail;
I'm a bit confused about how the `client.getBasicPersonDetailsFromEmail` would work, too, as it doesn't look like it's being called to me?

2022-07-08 14:44 UTC, simonfernandes commented
The tests need reviewing with whitespace hidden

2022-07-08 15:16 UTC, mr-field reviewed
The tests look good, I just have a minor improvement to suggest. Could you also add a test for when `getBasicUserDetailsByEmail` is called with an invalid token, for completeness?

2022-07-08 16:11 UTC, simonfernandes commented
I've added a test for invalid token... I think. I wasn't quite sure how to do it which is why I left it out. I think this covers it. The soap client method catches the exception and returns the result, which would be an object with null return value.

2022-07-08 16:12 UTC, simonfernandes commented on src/datasources/stfc/StfcUserDataSource.spec.ts
> +    expect(mockGetSearchableBasicPersonDetailsFromEmail).toBeCalled();
Thanks, I couldn't find the answer to that easily either, and it probably reads better too.

2022-07-08 16:16 UTC, mr-field approved these changes

2022-07-11 08:49 UTC, vyshnavi1605 approved these changes

2022-07-11 08:52 UTC, merged