Swap 2688 refactor openid integration
UserOfficeProject/user-office-backend pull request #707
Opened 2022-08-04 21:15 UTC by jekabs-karklins

## Description

This PR aims to add support for authentification with external identity providers using OpenId connect.

## Motivation and Context

As we are integrating with the Ping Identity Access Management platform which supports OpenId Connect which is simple identity layer on top of the OAuth 2.0 protocol, the implementation has been made generic, so that it is possible to use any other Identity Provider platform implementing the OpenId connect.

This PR contains also an example GoogleAuthorization class which shows how it can be easily done.

## How Has This Been Tested

- [x] Manual tests

## Fixes

https://jira.esss.lu.se/browse/SWAP-2688

## Changes

Implemented base class OpenIdConnectAuthorization
Added new Authorizers, PingAuthorization, and example GoogleAuthorization

## Depends on

https://github.com/UserOfficeProject/user-office-frontend/pull/965

2022-08-05 11:24 UTC, martin-trajanovski approved these changes
In general it looks good. Just few small comments left.

2022-08-05 11:24 UTC, martin-trajanovski commented on src/resolvers/types/User.ts
> +  public oidcAccessToken: string | null;
Is it possible to query the user Access token now directly on the user object? Not sure how safe this is but just wanted to check.

2022-08-09 11:19 UTC, jekabs-karklins commented on src/resolvers/types/User.ts
> +  public oidcAccessToken: string | null;
Yes, this should be removed. No need to expose it to the client.

2022-08-23 18:01 UTC, ACLay requested changes

2022-08-31 14:36 UTC, jekabs-karklins commented on src/config/ess/configureESSEnvironment.ts
> +      settingsId: SettingsId.EXTERNAL_AUTH_LOGIN_URL,
I kept the same flow as with STFC external auth (see) `configureSTFCEnvironment`. I agree that User officer should not change these values, and they are set here merely for client access. Changing the way the EXTERNAL_AUTH_LOGIN_URL is distributed could be a separate issue, and as this PR is already very large I would not want to add on top of it this change.

2022-08-31 16:51 UTC, ACLay commented on docker-compose.e2e.yml
> +      protocol: http
It looks like the use of this variable was removed in e343fe0c1336566212adac5f135f874bea6ff05c, can it be removed from here and `example.development.env`

2022-09-12 20:53 UTC, jekabs-karklins commented on src/auth/StfcUserAuthorization.ts
> +    } catch (error) {
I do not know, the reason, but I kept it as it was before to not change any flow for STFC authorization. This code used to sit in UserMutations, but I moved it in as the flow was STFC specific https://github.com/UserOfficeProject/user-office-backend/pull/707/files/f58e0e2445719c459fa49c23b113e4d39dfa6a90#diff-2590831eb92b22869cbdd92250fb1d366c439053179fa0c558765fb1313a111aL521

2022-09-14 09:32 UTC, ACLay requested changes

2022-09-14 09:32 UTC, ACLay commented on example.development.env
> +protocol=http
I don't think this variable is used anywhere now, can it be removed?

2022-09-14 09:32 UTC, ACLay commented on src/auth/EmailAsExternalTokenAuthorization.ts
> +export class EmailAsExternalTokenAuthorization extends UserAuthorization {
Not a necessity, but is there some way we can have this throw an error if it's used outside of tests? Maybe make it require an "allow insecure auth for tests" environment variable? An approve all authenticator seems like a risky thing to potentially have running in production

2022-09-14 09:32 UTC, ACLay commented on src/config/ess/configureESSEnvironment.ts
> +  if (OpenIdClient.hasConfiguration()) {
It looks like if the OpenID client is missing config the app will still continue. Is that the case, and if so, is that behaviour desired?

2022-09-14 09:32 UTC, ACLay commented on src/auth/mockups/UserAuthorization.ts
>    async externalTokenLogin(token: string): Promise<User | null> {
Should this UserAuthorization implementation also have a redirectUrl parameter added?

2022-09-14 09:32 UTC, ACLay commented on src/queries/UserQueries.ts
>  // TODO: Try to replace request-promise with axios. request-promise depends on request which is deprecated.
Since we've removed the request-promise import, can this comment be removed too

2022-09-15 07:33 UTC, jekabs-karklins commented on src/auth/mockups/UserAuthorization.ts
>    async externalTokenLogin(token: string): Promise<User | null> {
Yes, that's true

2022-09-15 08:34 UTC, jekabs-karklins commented on src/auth/EmailAsExternalTokenAuthorization.ts
> +export class EmailAsExternalTokenAuthorization extends UserAuthorization {
I have added the check, but I want to remove this Authorizer latter, as I don't think it is elegant

2022-09-15 10:00 UTC, jekabs-karklins commented on example.development.env
> +protocol=http
True

2022-09-15 10:07 UTC, jekabs-karklins commented on src/config/ess/configureESSEnvironment.ts
> +  if (OpenIdClient.hasConfiguration()) {
Yes, that is desired behavior. But I now see that the better fit for this setup is within the authorizer itself. So if you want to use this Auth all no need to do is map it in dependency config and set environmental variables

2022-09-15 10:08 UTC, jekabs-karklins commented on src/queries/UserQueries.ts
>  // TODO: Try to replace request-promise with axios. request-promise depends on request which is deprecated.
👌🏻

2022-10-20 14:50 UTC, closed without merging