refactor(graphql): rename getPageContent to pageContent
UserOfficeProject/user-office-backend pull request #709
Opened 2022-08-10 13:10 UTC by jekabs-karklins

## Description

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2022-08-15 11:20 UTC, martin-trajanovski requested changes

2022-08-15 11:20 UTC, martin-trajanovski commented on src/resolvers/queries/GetPageContentQuery.ts
>  @Resolver()
Maybe the file name should be also changed to just `PageContentQuery.ts`.

2022-08-15 12:24 UTC, jekabs-karklins commented on src/resolvers/queries/GetPageContentQuery.ts
>  @Resolver()
👍🏻

2022-08-15 12:25 UTC, martin-trajanovski approved these changes

2022-08-26 07:04 UTC, TickleThePanda approved these changes

2022-08-30 11:25 UTC, bolmsten approved these changes

2022-09-18 16:12 UTC, merged