refactor: rename query id params to have exact naming
UserOfficeProject/user-office-backend pull request #717
Opened 2022-08-12 12:52 UTC by jekabs-karklins

## Description

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2022-08-15 11:34 UTC, martin-trajanovski requested changes
This seems like a nice refactor to follow some general pattern throughout the application. The only concern that I have is that this will break the scheduler app because it is referencing the `User` and `BasicUserDetails` resolvers by `id` field. That should be changed now to reference by `userId` field instead. Let me know if you need some help with that but it should be pretty straight forward change. I will approve this after you create a PR in the scheduler with the needed changes.

2022-08-15 12:47 UTC, jekabs-karklins commented
> This seems like a nice refactor to follow some general pattern throughout the application. The only concern that I have is that this will break the scheduler app because it is referencing the `User`, `BasicUserDetails` and `Call` resolvers by `id` field. That should be changed now to reference by `userId`/`callId` field instead. Let me know if you need some help with that but it should be pretty straight forward change. I will approve this after you create a PR in the scheduler with the needed changes.

I had a similar concern and tested it, but there is actually no problem because the noun User still has the field "id". It's only the query param name that changes.

2022-08-15 12:48 UTC, martin-trajanovski commented
> > This seems like a nice refactor to follow some general pattern throughout the application. The only concern that I have is that this will break the scheduler app because it is referencing the `User`, `BasicUserDetails` and `Call` resolvers by `id` field. That should be changed now to reference by `userId`/`callId` field instead. Let me know if you need some help with that but it should be pretty straight forward change. I will approve this after you create a PR in the scheduler with the needed changes.
> 
> I had a similar concern and tested it, but there is actually no problem because the noun User still has the field "id". It's only the query param name that changes.

OK I understand. It is good that you have tested it.

2022-08-15 12:48 UTC, martin-trajanovski approved these changes

2022-08-17 08:43 UTC, keiranjprice101 approved these changes

2022-08-17 09:40 UTC, merged