Swap 1245 proposal workflows ui improvements
UserOfficeProject/user-office-backend pull request #99
Opened 2020-12-02 14:40 UTC by martin-trajanovski

## Description

Adding description to the events enum and cleanup

## Motivation and Context

It solves the problem about better explanation of the events in the app.

## How Has This Been Tested

E2e tests

## Fixes

https://jira.esss.lu.se/browse/SWAP-1245

## Tests included/Docs Updated?

- [x] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2020-12-03 07:57 UTC, peter-asztalos approved these changes

2020-12-03 11:11 UTC, jekabs-karklins approved these changes

2020-12-03 16:48 UTC, ACLay requested changes
Just a minor tweak and query, otherwise this is looking okay to me

2020-12-03 16:48 UTC, ACLay commented on src/events/event.enum.ts
> +  [Event.PROPOSAL_ALL_SEP_REVIEWERS_SELECTED, ''],
This event is missing a description

2020-12-03 16:48 UTC, ACLay commented on src/queries/ProposalSettingsQueries.ts
> +          eventItem.startsWith('PROPOSAL_') || eventItem.startsWith('CALL')
Should be `'CALL_'` to be consistent with `'PROPOSAL_'`?

2020-12-04 09:43 UTC, ACLay approved these changes

2020-12-04 14:51 UTC, merged